import Login from "@/components/Login/Login";
import React from "react";
export const metadata = {
  title: "Login pShope",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <Login />
    </div>
  );
};

export default page;
