import "./globals.css";
import Nav from "@/components/Navbar/Nav";
import ReduxProvider from "@/Redux/Provider/ReduxProvider";

export const metadata = {
  title: "pShop Online Market",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" mx-[8%]  bg-slate-900">
        <ReduxProvider>
          <Nav />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
// bg-[#002147]
