import PostForm from "@/components/PostAds/PostForm";
import React from "react";
export const metadata = {
  title: "Post Your Ads",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <PostForm />
    </div>
  );
};

export default page;
