export const areaLocations = {
  Dhaka: [
    "Select",
    "Mirpur",
    "Uttara",
    "Savar",
    "Mohammadpur",
    "Badda",
    "Jatrabari",
    "Gulshan",
    "Basundhara",
    "Baridhara",
    "Elephant Road",
    "Rampura",
    "Tongi",
    "Banani",
    "Malibag",
    "Basabo",
    "Tejgoan",
    "Demra",
  ],
  Chattogram: [
    "Select",
    "Aggrabad",
    "Chawkbazar",
    "Nasirabad",
    "kotwali",
    "Chandgoan",
    "Baizid",
    "Patenga",
    "Oxygen",
    "Cornelhat",
    "Muradpur",
    "bandar",
    "New Market",
    "Raozan",
  ],
  Sylhet: [
    "Select",
    "Zinda Bazar",
    "Bandar Bazar",
    "Amber Khana",
    "South Surma",
    "Shibganj",
    "Golapgonj",
    "Shahporan",
    "Mira Bazar",
    "Majortila",
    "Lama Bazar",
    "Osmani Nagar",
    "Kumar Para",
  ],
  Khulna: [
    "Select",
    "Khulna Sadar",
    "Daulatpur",
    "Sonadanga",
    "Boyra Bazar",
    "Rupsa",
    "Gollamari",
    "Nirala",
    "Zero Point",
    "Lobon Chora",
    "Moylapota",
    "Dacopy",
    "Koyra",
    "Pabla",
    "Khan Jahan Ali",
    "Tootpara",
  ],
  Barishal: [
    "Select",
    "Sadar Road",
    "Nattullabad",
    "Rupatali",
    "Gournaid",
    "Amtala",
    "Natun Bazar",
    "Beltola Feri Ghat",
    "Chand Mari",
    "Chawk Bazar",
    "Kali Zira",
  ],
  Rajshahi: [
    "Select",
    "New Market",
    "Shaheb Bazar",
    "Uposahar",
    "Court Station",
    "Kazla",
    "Motihar",
    "Boalia",
    "Rajpara",
    "Vodra",
    "Bagmara",
  ],
  Rangpur: [
    "Select",
    "Jahaj Company More",
    "Shapla Chottor",
    "Dhap",
    "Lalbag Mor",
    "Pourobazar",
    "Paglapir",
    "Tajhat",
    "Vinno Jogot",
    "G L Roy Road",
    "Shatrasta Mor",
  ],
  Mymensingh: [
    "Select",
    "Ganginar Par",
    "Valuka",
    "Chorpara",
    "Town Hall",
    "Muktagacha",
    "Phulpur",
    "Kistopur",
  ],
};

export const divitionLocation = [
  "Location",
  "Dhaka",
  "Rajshahi",
  "Sylhet",
  "Khulna",
  "Rangpur",
  "Barishal",
  "Chattogram",
  "Mymensingh",
];
export const accessoriesName = [
  "Laptops",
  "Desktop Computer",
  "Phone & Tablets Accessories",
  "Audio & Sound System",
  "Home Electronics",
  "Tv & Video Accessories",
  "Others",
];
// brand name
export const allBrandName = [
  "Accessories Type",
  "Laptop-Computer",
  "Mobile",
  "Car",
  "Tv-Led",
  "Bike",
  "Others",
];
export const corrospondingBrandAccessoriesName = {
  "Laptop-Computer": [
    "Select",
    "HP (Hewlett-Packard)",
    "Apple",
    "Dell",
    "Lenovo",
    "Asus",
    "Acer",
    "Microsoft",
    "MSI",
    "Samsung",
    "LG",
    "Razer",
    "Huawei",
    "Others",

    // Add more brands as needed
  ],
  Mobile: [
    "Select",
    "Apple",
    "Samsung",
    "Xiaomi",
    "Huawei",
    "Oppo",
    "Vivo",
    "OnePlus",
    "Google",
    "Motorola",
    "Sony",
    "Nokia",
    "LG",
    "Realme",
    "ASUS",
    "Lenovo",
    "Others",

    // Add more brands as needed
  ],
  Car: [
    "Select",
    "Toyota",
    "Volkswagen",
    "Ford",
    "Honda",
    "Chevrolet",
    "Nissan",
    "Mercedes-Benz",
    "BMW",
    "Audi",
    "Hyundai",
    "Kia",
    "Volvo",
    "Tesla",
    "Subaru",
    "Mitsubishi",
    "Others",
    // Add more brands as needed
  ],
  "Tv-Led": [
    "Select",
    "Samsung",
    "LG",
    "Sony",
    "TCL",
    "Panasonic",
    "Philips",
    "Toshiba",
    "Haier",
    "Xiaomi",
    "Insignia",
    "Others",
    // Add more brands as needed
  ],
  Bike: [
    "Select",
    "Honda",
    "Yamaha",
    "Suzuki",
    "BMW Motorrad",
    "KTM",
    "Tvs",
    "Discover",
    "Royal Enfield",
    "Bajaj",
    "Others",
    // Add more brands as needed
  ],
};

// corrosponding  model name

export const corrospondingModelNames = {
  "HP (Hewlett-Packard)": [
    "Select",
    "HP Spectre x360",
    "HP Envy 13",
    "HP Pavilion x360",
    "HP Omen 15",
    "HP Elite Dragonfly",
    "HP ProBook 450",
    "HP ZBook Firefly",
    "HP Chromebook 14",
    "HP DeskJet 2755",
    "HP LaserJet Pro MFP M479fdw",
    "HP ENVY 27",
    "HP VH240a",
    "HP EliteOne 800 G6",
    "HP Pavilion Gaming Desktop",
    "HP Slim S01-pF1046b",
    "Others",
  ],
  Apple: [
    // iPhones
    "Select",
    "iPhone 13",
    "iPhone 13 mini",
    "iPhone 13 Pro",
    "iPhone 13 Pro Max",
    "iPhone 12",
    "iPhone 12 mini",
    "iPhone 12 Pro",
    "iPhone 12 Pro Max",
    "iPhone SE (2nd generation)",
    "iPhone 11",
    "iPhone 11 Pro",
    "iPhone 11 Pro Max",
    "iPhone XR",
    "iPhone XS",
    "iPhone XS Max",
    "iPhone X",
    "iPhone 8",
    "iPhone 8 Plus",

    // iPads
    "iPad (9th generation)",
    "iPad mini (6th generation)",
    "iPad Air (4th generation)",
    "iPad Pro 12.9-inch (5th generation)",
    "iPad Pro 11-inch (3rd generation)",
    "iPad (8th generation)",
    "iPad Air (3rd generation)",
    "iPad Pro 12.9-inch (4th generation)",
    "iPad Pro 11-inch (2nd generation)",

    // MacBooks and Macs
    "MacBook Air",
    "MacBook Pro 13-inch",
    "MacBook Pro 14-inch",
    "MacBook Pro 16-inch",
    "iMac 24-inch",
    "iMac 27-inch",
    "Mac mini",
    "Mac Pro",
    "Othres",
  ],
  Dell: [
    "Select",
    "Dell XPS 13",
    "Dell XPS 15",
    "Dell Inspiron 15",
    "Dell Inspiron 13",
    "Dell Latitude 7000 Series",
    "Dell Precision 5000 Series",
    "Dell Alienware m15",
    "Dell G3",
    "Dell Vostro 15",
    "Dell Chromebook 13",
    "Others",
  ],
  Lenovo: [
    "Select",
    "Lenovo ThinkPad X1 Carbon",
    "Lenovo ThinkPad X1 Yoga",
    "Lenovo ThinkPad T14s",
    "Lenovo ThinkPad X1 Fold",
    "Lenovo Yoga 9i",
    "Lenovo Yoga 7i",
    "Lenovo Legion 5",
    "Lenovo Legion 7i",
    "Lenovo IdeaPad Slim 7",
    "Lenovo IdeaPad Flex 5",
    "Lenovo IdeaCentre 5",
    "Lenovo IdeaCentre AIO 3",
    "Lenovo Tab P11 Pro",
    "Lenovo Tab M10",
    "Lenovo Tab M8",
    "Others",
  ],
  Asus: [
    "Select",
    "Asus ROG Zephyrus G14",
    "Asus ROG Zephyrus G15",
    "Asus ZenBook 14",
    "Asus ZenBook Flip S",
    "Asus VivoBook S15",
    "Asus TUF Gaming A15",
    "Asus ROG Strix Scar 15",
    "Asus ROG Strix G15",
    "Asus Chromebook Flip C434",
    "Asus ROG Swift PG279Q",
    "Asus VG248QE",
    "Asus ROG Rapture GT-AX11000",
    "Asus Prime X570-P",
    "Asus ROG Crosshair VIII Hero",
    "Asus ProArt Display PA278QV",
    "Others",
  ],
  ASUS: [
    "Select",
    "ASUS ROG Phone 5",
    "ASUS ROG Phone 3",
    "ASUS ZenFone 8",
    "ASUS ZenFone 7 Pro",
    "ASUS ZenFone 6",
    "ASUS ZenFone 5Z",
    "ASUS ZenFone Max Pro M2",
    "ASUS ZenFone Max Pro M1",
    "ASUS ZenFone 5 Lite",
    "ASUS ZenFone 4 Selfie Pro",
    "ASUS ZenFone 4 Max",
    "ASUS ZenFone 3 Deluxe",
    "ASUS ZenFone 3 Zoom",
    "ASUS ZenFone 3 Laser",
    "ASUS ZenFone 2",
    "ASUS ZenFone Max",
    "ASUS ZenFone Go",
    "ASUS ZenFone Live",
    "ASUS ZenFone AR",
    "ASUS ZenFone V",
    "Others",
  ],
  Acer: [
    "Select",
    "Acer Swift 3",
    "Acer Aspire 5",
    "Acer Predator Helios 300",
    "Acer Nitro 5",
    "Acer Spin 5",
    "Acer Chromebook Spin 713",
    "Acer ConceptD 7",
    "Acer TravelMate P6",
    "Acer Predator XB271HU",
    "Acer Nitro XV272U",
    "Acer Predator Orion 9000",
    "Acer Aspire TC",
    "Acer Aspire C24",
    "Acer Predator X34",
    "Acer Swift 7",
    "Others",
  ],
  Microsoft: [
    "Select",
    "Surface Pro 7",
    "Surface Laptop 4",
    "Surface Book 3",
    "Surface Go 3",
    "Surface Studio 2",
    "Surface Duo",
    "Surface Pro X",
    "Surface Laptop Go",
    "Surface Pro 8",
    "Surface Go 2",
    "Xbox Series X",
    "Xbox Series S",
    "Xbox One X",
    "Microsoft Modern Keyboard",
    "Microsoft Arc Mouse",
    "Others",
  ],
  MSI: [
    "Select",
    "MSI GS66 Stealth",
    "MSI GE76 Raider",
    "MSI Prestige 14",
    "MSI Creator 17",
    "MSI Bravo 15",
    "MSI Modern 14",
    "MSI MPG Z590 GAMING CARBON WIFI",
    "MSI MAG B550 TOMAHAWK",
    "MSI GeForce RTX 3080 GAMING X TRIO",
    "MSI Radeon RX 6800 XT GAMING X TRIO",
    "MSI Optix MAG274QRF-QD",
    "MSI Optix MPG341CQR",
    "MSI Optix G271",
    "MSI Optix MAG322CQR",
    "MSI Optix MAG161V",
    "Others",
  ],
  Samsung: [
    "Select",
    // Mobile Phones
    "Samsung Galaxy S21 Ultra",
    "Samsung Galaxy S21+",
    "Samsung Galaxy S21",
    "Samsung Galaxy Note 20 Ultra",
    "Samsung Galaxy Note 20",
    "Samsung Galaxy Z Fold 3",
    "Samsung Galaxy Z Flip 3",
    "Samsung Galaxy A52",
    "Samsung Galaxy A32",
    "Samsung Galaxy A72",
    "Samsung Galaxy M32",
    "Samsung Galaxy M52",
    "Samsung Galaxy M12",
    "Samsung Galaxy F62",
    "Samsung Galaxy Xcover Pro",
    "Samsung Galaxy S20 FE",
    "Samsung Galaxy S20",
    "Samsung Galaxy S20+",
    "Samsung Galaxy S20 Ultra",
    "Samsung Galaxy Note 10",
    "Samsung Galaxy Note 10+",
    "Samsung Galaxy A71",
    "Samsung Galaxy A51",
    "Samsung Galaxy A21s",
    "Samsung Galaxy A11",
    "Samsung Galaxy M31",
    "Samsung Galaxy M21",
    "Samsung Galaxy M11",
    "Samsung Galaxy M01",
    "Samsung Galaxy A02s",
    "Samsung Galaxy A12",
    "Samsung Galaxy F41",
    "Samsung Galaxy S10",
    "Samsung Galaxy S10+",
    "Samsung Galaxy S10e",
    "Samsung Galaxy Note 9",
    "Samsung Galaxy A70",
    "Samsung Galaxy A50",
    "Samsung Galaxy A30s",
    "Samsung Galaxy M30s",
    "Samsung Galaxy M20",
    "Samsung Galaxy M10",
    "Samsung Galaxy A20",
    "Samsung Galaxy A10",
    "Samsung Galaxy J7 Prime",
    "Samsung Galaxy J6+",
    "Samsung Galaxy J4+",
    "Samsung Galaxy J2 Core",
    "Samsung Galaxy J2 Pro",
    "Samsung Galaxy J1 Mini",
    "Samsung Galaxy J1 Ace",

    // Laptops
    "Samsung Galaxy Book Flex 2",
    "Samsung Galaxy Book Pro",
    "Samsung Galaxy Book Ion",
    "Samsung Galaxy Book S",
    "Samsung Galaxy Chromebook",
    "Samsung Notebook 9 Pro",
    "Samsung Notebook 7 Spin",
    "Samsung Notebook Flash",
    "Samsung Notebook Odyssey",
    "Samsung Notebook 9 Pen",
    "Samsung Notebook 5",
    "Samsung Notebook 3",
    "Samsung Ativ Book 9",

    // TVs
    "Samsung QN900A Neo QLED 8K TV",
    "Samsung QN800A Neo QLED 8K TV",
    "Samsung QN90A Neo QLED 4K TV",
    "Samsung QN85A Neo QLED 4K TV",
    "Samsung QN80A Neo QLED 4K TV",
    "Samsung Q60A QLED 4K TV",
    "Samsung AU9000 Crystal UHD 4K TV",
    "Samsung AU8000 Crystal UHD 4K TV",
    "Samsung AU7700 Crystal UHD 4K TV",
    "Samsung TU8300 Curved Crystal UHD 4K TV",
    "Samsung TU8000 Crystal UHD 4K TV",
    "Samsung The Frame 4K TV",
    "Samsung The Serif 4K TV",
    "Samsung The Sero 4K TV",
  ],
  LG: [
    "Select",
    "LG Velvet",
    "LG Wing",
    "LG V60 ThinQ",
    "LG G8 ThinQ",
    "LG G8X ThinQ",
    "LG K92 5G",
    "LG Stylo 6",
    "LG Q92",
    "LG Gram 17",
    "LG Gram 15",
    "LG Gram 14",
    "LG Gram 2-in-1 14",
    "LG UltraGear 27GL850-B",
    "LG UltraFine 5K Display",
    "LG UltraWide 34WN80C-B",
    "LG UltraFine Ergo 32UN880-B",
    "LG 27UK650-W",
    "LG All-in-One 24V770",
    "LG Ultra PC 17U70N",
    "LG Gram 2-in-1 16T90P",
    "LG UltraGear 38GN950-B",
    "LG Gram 16Z90P",
    "LG UltraWide 38WN95C-W",
    "LG UltraFine OLED Pro 32EP950",
    "LG Gram 17Z90P",
    "Others",
  ],
  Razer: [
    "Select",
    "Razer Phone",
    "Razer Phone 2",
    "Razer Blade 15",
    "Razer Blade 17",
    "Razer Blade Stealth",
    "Razer Blade Pro 17",
    "Razer Blade Pro 15",
    "Razer Blade 14",
    "Razer Book 13",
    "Razer Book 15",
    "Razer Huntsman Elite Keyboard",
    "Razer BlackWidow V3 Keyboard",
    "Razer DeathAdder Elite Mouse",
    "Razer Naga Trinity Mouse",
    "Razer Viper Ultimate Mouse",
    "Razer Basilisk Ultimate Mouse",
    "Razer Kraken Headset",
    "Razer BlackShark V2 Headset",
    "Razer Hammerhead True Wireless Earbuds",
    "Razer Orochi Mouse",
    "Razer Tartarus Keypad",
    "Razer Firefly Mouse Mat",
    "Razer Goliathus Mouse Mat",
    "Razer Kiyo Webcam",
    "Razer Seiren X Microphone",
    "Others",
  ],
  Huawei: [
    "Select",
    "Huawei P40",
    "Huawei P40 Pro",
    "Huawei Mate 40",
    "Huawei Mate 40 Pro",
    "Huawei Mate 40 Pro+",
    "Huawei Nova 8",
    "Huawei Nova 8 Pro",
    "Huawei MateBook X Pro",
    "Huawei MateBook D 15",
    "Huawei MateBook 13",
    "Huawei MateBook 14",
    "Huawei MatePad Pro",
    "Huawei MatePad Pro 12.6",
    "Huawei MediaPad M6",
    "Huawei MediaPad M5 Lite",
    "Huawei FreeBuds 4",
    "Huawei FreeBuds Pro",
    "Huawei Watch GT 2",
    "Huawei Watch GT 2 Pro",
    "Huawei Band 6",
    "Huawei MateStation S",
    "Huawei MatePad 10.4",
    "Huawei MatePad T8",
    "Huawei MateView",
    "Huawei MateView GT",
  ],
  Xiaomi: [
    "Select",
    "Xiaomi Mi 11",
    "Xiaomi Mi 11 Ultra",
    "Xiaomi Mi 11i",
    "Xiaomi Mi 11 Lite",
    "Xiaomi Mi 11 Lite 5G",
    "Xiaomi Mi 11X",
    "Xiaomi Redmi Note 10",
    "Xiaomi Redmi Note 10 Pro",
    "Xiaomi Redmi Note 10S",
    "Xiaomi Redmi Note 9",
    "Xiaomi Redmi Note 9 Pro",
    "Xiaomi Redmi Note 9T",
    "Xiaomi Redmi 9",
    "Xiaomi Redmi 9A",
    "Xiaomi Redmi 9C",
    "Xiaomi Mi Notebook Pro X 15",
    "Xiaomi Mi Notebook Pro 14",
    "Xiaomi Mi Notebook Ultra",
    "Xiaomi Mi Notebook Air 13.3",
    "Xiaomi Mi Notebook 14",
    "Xiaomi Mi Notebook Horizon Edition",
    "Xiaomi Mi Gaming Laptop",
    "Xiaomi RedmiBook 15",
    "Xiaomi RedmiBook 14",
    "Xiaomi RedmiBook Pro 14",
    "Others",
  ],
  Oppo: [
    "Select",
    "Oppo Find X3 Pro",
    "Oppo Find X3 Neo",
    "Oppo Find X3 Lite",
    "Oppo Reno6 Pro+",
    "Oppo Reno6 Pro",
    "Oppo Reno6",
    "Oppo Reno6 Z",
    "Oppo Reno5 Pro+",
    "Oppo Reno5 Pro",
    "Oppo Reno5",
    "Oppo Reno5 Z",
    "Oppo Reno4 Pro",
    "Oppo Reno4",
    "Oppo Reno4 Z",
    "Oppo A95 5G",
    "Oppo A94",
    "Oppo A74",
    "Oppo A54",
    "Oppo A53",
    "Oppo A16",
    "Oppo A15",
    "Oppo F19 Pro+",
    "Oppo F19 Pro",
    "Oppo F19",
    "Oppo F17 Pro",
    "Others",
  ],
  Vivo: [
    "Select",
    "Vivo X60 Pro+",
    "Vivo X60 Pro",
    "Vivo X60",
    "Vivo V21e",
    "Vivo V21 5G",
    "Vivo V21e 5G",
    "Vivo V21",
    "Vivo Y72 5G",
    "Vivo Y52s",
    "Vivo Y31s",
    "Vivo Y20G",
    "Vivo Y20s",
    "Vivo Y51s",
    "Vivo Y20",
    "Vivo Y30",
    "Vivo Y12s",
    "Vivo Y11s",
    "Vivo Y1s",
    "Vivo S9",
    "Vivo S7t",
    "Vivo S7e",
    "Vivo S7",
    "Vivo iQOO 7",
    "Vivo iQOO Neo5",
    "Vivo iQOO Z3",
    "Others",
  ],
  OnePlus: [
    "Select",
    "OnePlus 9 Pro",
    "OnePlus 9",
    "OnePlus 9R",
    "OnePlus 8T",
    "OnePlus 8 Pro",
    "OnePlus 8",
    "OnePlus Nord 2",
    "OnePlus Nord CE 5G",
    "OnePlus Nord",
    "OnePlus 7T Pro",
    "OnePlus 7T",
    "OnePlus 7 Pro",
    "OnePlus 7",
    "OnePlus 6T",
    "OnePlus 6",
    "OnePlus 5T",
    "OnePlus 5",
    "OnePlus 3T",
    "OnePlus 3",
    "OnePlus Nord N200",
    "OnePlus Nord N10 5G",
    "OnePlus Nord N100",
    "OnePlus X",
    "OnePlus One",
    "OnePlus 2",
    "Others",
  ],
  Google: [
    "Select",
    "Google Pixel 6 Pro",
    "Google Pixel 6",
    "Google Pixel 5a",
    "Google Pixel 5",
    "Google Pixel 4a 5G",
    "Google Pixel 4a",
    "Google Pixel 4 XL",
    "Google Pixel 4",
    "Google Pixel 3a XL",
    "Google Pixel 3a",
    "Google Pixel 3 XL",
    "Google Pixel 3",
    "Google Pixel 2 XL",
    "Google Pixel 2",
    "Google Pixel XL",
    "Google Pixel",
    "Google Nexus 6P",
    "Google Nexus 6",
    "Google Nexus 5X",
    "Google Nexus 5",
    "Google Nexus 4",
    "Google Nexus S",
    "Google Nexus One",
    "Google Nexus",
    "Google Pixel C",
    "Others",
  ],
  Motorola: [
    "Select",
    "Motorola Edge 20 Pro",
    "Motorola Edge 20",
    "Motorola Edge 20 Lite",
    "Motorola Moto G60",
    "Motorola Moto G40 Fusion",
    "Motorola Moto G30",
    "Motorola Moto G10",
    "Motorola Moto G Power (2021)",
    "Motorola Moto G Stylus (2021)",
    "Motorola Moto G9 Power",
    "Motorola Moto G9 Play",
    "Motorola Moto G8 Power",
    "Motorola Moto G8 Plus",
    "Motorola Moto G7 Power",
    "Motorola Moto G6 Plus",
    "Motorola Moto G5S Plus",
    "Motorola Moto G4 Plus",
    "Motorola Moto X Style",
    "Motorola Moto X Play",
    "Motorola Moto X Force",
    "Motorola Moto X4",
    "Motorola Moto X5",
    "Motorola Moto Z3",
    "Motorola Moto Z4",
    "Motorola Moto Z5",
    "Others",
  ],
  Sony: [
    "Select",
    "Sony Xperia 1 III",
    "Sony Xperia 5 III",
    "Sony Xperia 10 III",
    "Sony Xperia 1 II",
    "Sony Xperia 5 II",
    "Sony Xperia 10 II",
    "Sony Xperia 1",
    "Sony Xperia 5",
    "Sony Xperia 10",
    "Sony Xperia XZ3",
    "Sony Xperia XZ2 Premium",
    "Sony Xperia XZ2",
    "Sony Xperia XZ1",
    "Sony Xperia XZ Premium",
    "Sony Xperia XZs",
    "Sony Xperia XZ",
    "Sony Xperia XA2 Ultra",
    "Sony Xperia XA2",
    "Sony Xperia XA1 Ultra",
    "Sony Xperia XA1 Plus",
    "Sony Xperia XA1",
    "Sony Xperia XA Ultra",
    "Sony Xperia XA",
    "Sony Xperia L4",
    "Sony Xperia L3",
    "Others",
  ],
  Nokia: [
    "Select",
    "Nokia G300",
    "Nokia G50",
    "Nokia G20",
    "Nokia G10",
    "Nokia X20",
    "Nokia X10",
    "Nokia C30",
    "Nokia C20 Plus",
    "Nokia C20",
    "Nokia 5.4",
    "Nokia 3.4",
    "Nokia 2.4",
    "Nokia 8.3 5G",
    "Nokia 5.3",
    "Nokia 1.4",
    "Nokia 1.3",
    "Nokia 7.2",
    "Nokia 6.2",
    "Nokia 4.2",
    "Nokia 3.2",
    "Nokia 2.3",
    "Nokia 1 Plus",
    "Nokia 9 PureView",
    "Nokia 8.1",
    "Nokia 7.1",
    "Others",
  ],
  Realme: [
    "Select",
    "Realme GT 2 Pro",
    "Realme GT 2",
    "Realme GT Neo 3",
    "Realme GT Neo 2",
    "Realme 9 Pro+",
    "Realme 9 Pro",
    "Realme 9",
    "Realme 8 Pro",
    "Realme 8",
    "Realme 8i",
    "Realme 8s",
    "Realme 7 Pro",
    "Realme 7",
    "Realme 7i",
    "Realme 6 Pro",
    "Realme 6",
    "Realme 6i",
    "Realme 5 Pro",
    "Realme 5",
    "Realme Narzo 50A",
    "Realme Narzo 50i",
    "Realme Narzo 50",
    "Realme Narzo 40",
    "Realme Narzo 30A",
    "Realme Narzo 30 Pro",
    "Others",
  ],
  Toyota: [
    "Select",
    "Toyota Corolla",
    "Toyota Camry",
    "Toyota RAV4",
    "Toyota Highlander",
    "Toyota Tacoma",
    "Toyota Tundra",
    "Toyota Prius",
    "Toyota 4Runner",
    "Toyota Sienna",
    "Toyota Avalon",
    "Toyota C-HR",
    "Toyota Supra",
    "Toyota Yaris",
    "Toyota Land Cruiser",
    "Toyota Sequoia",
    "Others",
  ],
  Volkswagen: [
    "Select",
    "Volkswagen Golf",
    "Volkswagen Jetta",
    "Volkswagen Passat",
    "Volkswagen Tiguan",
    "Volkswagen Atlas",
    "Volkswagen Arteon",
    "Volkswagen Taos",
    "Volkswagen ID.4",
    "Volkswagen Beetle",
    "Volkswagen Touareg",
    "Volkswagen Atlas Cross Sport",
    "Volkswagen Golf GTI",
    "Volkswagen Golf R",
    "Volkswagen e-Golf",
    "Volkswagen Amarok",
    "Others",
  ],
  Ford: [
    "Select",
    "Ford Mustang",
    "Ford F-150",
    "Ford Explorer",
    "Ford Escape",
    "Ford Ranger",
    "Ford Edge",
    "Ford Fusion",
    "Ford Fiesta",
    "Ford Bronco",
    "Ford EcoSport",
    "Ford Expedition",
    "Ford Focus",
    "Ford Transit",
    "Ford Taurus",
    "Ford Flex",
    "Others",
  ],
  Honda: [
    "Select",
    "Honda Accord",
    "Honda Civic",
    "Honda CR-V",
    "Honda Pilot",
    "Honda Odyssey",
    "Honda HR-V",
    "Honda Fit",
    "Honda Ridgeline",
    "Honda Passport",
    "Honda Insight",
    "Honda Clarity",
    "Honda Crosstour",
    "Honda Element",
    "Honda Prelude",
    "Honda S2000",
    "Others",
  ],
  Chevrolet: [
    "Select",
    "Chevrolet Silverado",
    "Chevrolet Equinox",
    "Chevrolet Traverse",
    "Chevrolet Malibu",
    "Chevrolet Camaro",
    "Chevrolet Tahoe",
    "Chevrolet Suburban",
    "Chevrolet Trailblazer",
    "Chevrolet Colorado",
    "Chevrolet Impala",
    "Chevrolet Blazer",
    "Chevrolet Sonic",
    "Chevrolet Spark",
    "Chevrolet Volt",
    "Chevrolet Corvette",
    "Others",
  ],
  Nissan: [
    "Select",
    "Nissan Altima",
    "Nissan Rogue",
    "Nissan Sentra",
    "Nissan Murano",
    "Nissan Pathfinder",
    "Nissan Maxima",
    "Nissan Versa",
    "Nissan Titan",
    "Nissan Frontier",
    "Nissan Armada",
    "Nissan Kicks",
    "Nissan Leaf",
    "Nissan Juke",
    "Nissan 370Z",
    "Nissan GT-R",
    "Others",
  ],
  "Mercedes-Benz": [
    "Select",
    "Mercedes-Benz A-Class",
    "Mercedes-Benz C-Class",
    "Mercedes-Benz E-Class",
    "Mercedes-Benz S-Class",
    "Mercedes-Benz CLA-Class",
    "Mercedes-Benz CLS-Class",
    "Mercedes-Benz GLA-Class",
    "Mercedes-Benz GLC-Class",
    "Mercedes-Benz GLE-Class",
    "Mercedes-Benz GLS-Class",
    "Mercedes-Benz G-Class",
    "Mercedes-Benz SL-Class",
    "Mercedes-Benz AMG GT",
    "Mercedes-Benz EQC",
    "Mercedes-Benz V-Class",
    "Others",
  ],
  BMW: [
    "Select",
    "BMW 3 Series",
    "BMW 5 Series",
    "BMW 7 Series",
    "BMW X1",
    "BMW X3",
    "BMW X5",
    "BMW X7",
    "BMW 2 Series",
    "BMW 4 Series",
    "BMW 8 Series",
    "BMW Z4",
    "BMW i3",
    "BMW i8",
    "BMW M2",
    "BMW M5",
    "Others",
  ],
  Audi: [
    "Select",
    "Audi A3",
    "Audi A4",
    "Audi A6",
    "Audi A8",
    "Audi Q3",
    "Audi Q5",
    "Audi Q7",
    "Audi Q8",
    "Audi TT",
    "Audi R8",
    "Audi RS3",
    "Audi RS4",
    "Audi RS5",
    "Audi RS6",
    "Audi e-tron",
    "Others",
  ],
  Hyundai: [
    "Select",
    "Hyundai Elantra",
    "Hyundai Sonata",
    "Hyundai Accent",
    "Hyundai Tucson",
    "Hyundai Santa Fe",
    "Hyundai Kona",
    "Hyundai Venue",
    "Hyundai Palisade",
    "Hyundai Ioniq",
    "Hyundai Veloster",
    "Hyundai Nexo",
    "Hyundai Azera",
    "Hyundai Genesis",
    "Hyundai Starex",
    "Hyundai Equus",
    "Others",
  ],
  Kia: [
    "Select",
    "Kia Forte",
    "Kia Optima",
    "Kia K5",
    "Kia Cadenza",
    "Kia Stinger",
    "Kia Soul",
    "Kia Seltos",
    "Kia Sportage",
    "Kia Sorento",
    "Kia Telluride",
    "Kia Rio",
    "Kia K900",
    "Kia Carnival",
    "Kia Niro",
    "Kia EV6",
    "Others",
  ],
  Volvo: [
    "Select",
    "Volvo S60",
    "Volvo S90",
    "Volvo V60",
    "Volvo V90",
    "Volvo XC40",
    "Volvo XC60",
    "Volvo XC90",
    "Volvo XC60 Recharge",
    "Volvo XC90 Recharge",
    "Volvo S60 Recharge",
    "Volvo S90 Recharge",
    "Volvo V60 Recharge",
    "Volvo V90 Recharge",
    "Volvo C40 Recharge",
    "Volvo Polestar 2",
    "Others",
  ],
  Tesla: [
    "Select",
    "Tesla Model S",
    "Tesla Model 3",
    "Tesla Model X",
    "Tesla Model Y",
    "Tesla Roadster",
    "Tesla Cybertruck",
    "Tesla Semi",
    "Tesla Model S Plaid",
    "Tesla Model 3 Standard Range Plus",
    "Tesla Model 3 Long Range",
    "Tesla Model 3 Performance",
    "Tesla Model Y Long Range",
    "Tesla Model Y Performance",
    "Tesla Model X Long Range",
    "Tesla Model X Plaid",
    "Others",
  ],
  Subaru: [
    "Select",
    "Subaru Impreza",
    "Subaru Legacy",
    "Subaru Outback",
    "Subaru Forester",
    "Subaru Crosstrek",
    "Subaru Ascent",
    "Subaru WRX",
    "Subaru BRZ",
    "Subaru XV",
    "Subaru Baja",
    "Subaru Tribeca",
    "Subaru Loyale",
    "Subaru SVX",
    "Subaru Justy",
    "Subaru XT",
    "Others",
  ],
  Mitsubishi: [
    "Select",
    "Mitsubishi Mirage",
    "Mitsubishi Mirage G4",
    "Mitsubishi Lancer",
    "Mitsubishi Outlander",
    "Mitsubishi Outlander Sport",
    "Mitsubishi Eclipse Cross",
    "Mitsubishi ASX",
    "Mitsubishi Triton",
    "Mitsubishi Pajero",
    "Mitsubishi Pajero Sport",
    "Mitsubishi Xpander",
    "Mitsubishi Attrage",
    "Mitsubishi Colt",
    "Mitsubishi Galant",
    "Mitsubishi i-MiEV",
    "Others",
  ],
  TCL: [
    "Select",
    "TCL 6-Series",
    "TCL 5-Series",
    "TCL 4-Series",
    "TCL 8-Series",
    "TCL S-Series",
    "TCL P-Series",
    "TCL R635",
    "TCL C715",
    "TCL X915",
    "TCL QLED 4K C815",
    "Others",
  ],
  Panasonic: [
    "Select",
    "Panasonic JX600 Series",
    "Panasonic HX600 Series",
    "Panasonic HX800 Series",
    "Panasonic HX940 Series",
    "Panasonic HZ1000 Series",
    "Panasonic HZ1500 Series",
    "Panasonic HZ2000 Series",
    "Panasonic JZ1000 Series",
    "Panasonic JZ1500 Series",
    "Panasonic JZ2000 Series",
    "Others",
  ],
  Philips: [
    "Select",
    "Philips 242B1H",
    "Philips 272E1CA",
    "Philips 276E9QDSB",
    "Philips 328E1CA",
    "Philips 272V8A",
    "Philips 278E1A",
    "Philips 346B1C",
    "Philips 328P6VUBREB",
    "Philips 242B1G",
    "Philips 328B6QJEB",
    "Others",
  ],
  Haier: [
    "Select",
    "Haier LE32K6500AG",
    "Haier LE40K6500AG",
    "Haier LE50K6500UA",
    "Haier LE55K6500UA",
    "Haier LE65K6500UA",
    "Haier LE32B9100T",
    "Haier LE43B9100T",
    "Haier LE49B9100T",
    "Haier LE55B9100U",
    "Haier LE65B9100U",
    "Others",
  ],
  Insignia: [
    "Select",
    "Insignia NS-24DF310NA21",
    "Insignia NS-32DF310NA19",
    "Insignia NS-39DF310NA21",
    "Insignia NS-43DF710NA21",
    "Insignia NS-50DF710NA21",
    "Insignia NS-55DF710NA21",
    "Insignia NS-24ER310NA17",
    "Insignia NS-32DR310NA17",
    "Insignia NS-39DR510NA17",
    "Insignia NS-50DR710NA17",
    "Others",
  ],
  Yamaha: [
    "Select",
    "Yamaha YZF-R1",
    "Yamaha YZF-R6",
    "Yamaha MT-09",
    "Yamaha MT-07",
    "Yamaha MT-03",
    "Yamaha FZ-09",
    "Yamaha FZ-07",
    "Yamaha XSR900",
    "Yamaha XSR700",
    "Yamaha Tenere 700",
    "Others",
  ],
  Suzuki: [
    "Select",
    "Hayabusa",
    "GSX-R1000",
    "GSX-R750",
    "GSX-R600",
    "V-Strom 650",
    "V-Strom 1050",
    "SV650",
    "Boulevard M109R",
    "Boulevard C50",
    "DR-Z400S",
    "DR650S",
    "RM-Z250",
    "RM-Z450",
    "GSX250R",
    "Burgman 400",
    "Others",
  ],
  "BMW Motorrad": [
    "Select",
    "BMW S 1000 RR",
    "BMW R 1250 GS",
    "BMW R 1250 RT",
    "BMW F 850 GS",
    "BMW F 750 GS",
    "BMW R nineT",
    "BMW K 1600 GTL",
    "BMW G 310 R",
    "BMW G 310 GS",
    "BMW S 1000 XR",
    "BMW R 18",
    "BMW R 1250 R",
    "BMW C 400 X",
    "BMW C 650 GT",
    "BMW S 1000 R",
    "Others",
  ],
  KTM: [
    "Select",
    "KTM Duke 125",
    "KTM Duke 200",
    "KTM Duke 250",
    "KTM Duke 390",
    "KTM RC 125",
    "KTM RC 200",
    "KTM RC 250",
    "KTM RC 390",
    "KTM 125 SX",
    "KTM 150 SX",
    "KTM 250 SX",
    "KTM 350 SX-F",
    "KTM 450 SX-F",
    "KTM 690 Duke",
    "KTM 1290 Super Duke R",
    "Others",
  ],
  Tvs: [
    "Select",
    "TVS Apache RTR 160",
    "TVS Apache RTR 180",
    "TVS Apache RTR 200 4V",
    "TVS Apache RR 310",
    "TVS Jupiter",
    "TVS Ntorq 125",
    "TVS Star City Plus",
    "TVS Radeon",
    "TVS Sport",
    "TVS XL 100",
    "TVS Scooty Pep+",
    "TVS Victor",
    "TVS Wego",
    "TVS Apache RTR 160 4V",
    "TVS iQube Electric",
    "Others",
  ],
  Discover: [
    "Select",
    "Bajaj Discover 100",
    "Bajaj Discover 125",
    "Bajaj Discover 135",
    "Bajaj Discover 150",
    "Bajaj Discover 110",
    "Bajaj Discover 125 ST",
    "Bajaj Discover 125 M",
    "Bajaj Discover 150S",
    "Bajaj Discover 125T",
    "Bajaj Discover 125F",
    "Bajaj Discover 125 Disc",
    "Bajaj Discover 100T",
    "Bajaj Discover 100M",
    "Bajaj Discover 125 Drum",
    "Bajaj Discover 110 Disc",
    "Others",
  ],
  "Royal Enfield": [
    "Select",
    "Royal Enfield Bullet 350",
    "Royal Enfield Classic 350",
    "Royal Enfield Meteor 350",
    "Royal Enfield Himalayan",
    "Royal Enfield Continental GT 650",
    "Royal Enfield Interceptor 650",
    "Royal Enfield Bullet 500",
    "Royal Enfield Classic 500",
    "Royal Enfield Thunderbird 350",
    "Royal Enfield Thunderbird 500",
    "Royal Enfield Bullet Trials 350",
    "Royal Enfield Bullet Trials 500",
    "Royal Enfield Classic Chrome",
    "Royal Enfield Classic Desert Storm",
    "Royal Enfield Classic Battle Green",
    "Others",
  ],
  Bajaj: [
    "Select",
    "Bajaj Pulsar 150",
    "Bajaj Pulsar 180",
    "Bajaj Pulsar 220F",
    "Bajaj Pulsar NS160",
    "Bajaj Pulsar NS200",
    "Bajaj Pulsar RS200",
    "Bajaj Platina 100",
    "Bajaj Platina 110",
    "Bajaj Avenger Street 160",
    "Bajaj Avenger Cruise 220",
    "Bajaj CT 100",
    "Bajaj Dominar 250",
    "Bajaj Dominar 400",
    "Bajaj V15",
    "Bajaj Discover 125",
    "Others",
  ],
};
