import ProductSection from "@/components/Product/ProductSection";
export const metadata = {
  title: "All Product Details",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <ProductSection />
    </div>
  );
};

export default page;
