import ProductDetailsPage from "@/components/Product Details/ProductDetailsPage";
// export const metadata = {
//   title: "Single Product Details",
//   description: "Generated by create next app",
// };
const page = () => {
  return (
    <div>
      <ProductDetailsPage />
    </div>
  );
};

export default page;
